=== jhinAza/rocket-player/www/userSettings/user_settings.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="settings">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="theme">
          <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="resources">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="sign_language">
                <xsd:complexType>
                  <xsd:attribute name="toggle" type="xsd:string" use="required"/>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="subtitles">
                <xsd:complexType>
                  <xsd:attribute name="toggle" type="xsd:string" use="required"/>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="transcription">
                <xsd:complexType>
                  <xsd:attribute name="toggle" type="xsd:string" use="required"/>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="dubbing">
                <xsd:complexType>
                  <xsd:attribute name="toggle" type="xsd:string" use="required"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="languages">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="language" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:attribute name="lang" type="xsd:string"/>
                  <xsd:attribute name="order" type="xsd:int"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="user_id" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== jhinAza/rocket-player/www/userSettings/default.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="user_settings.xsd" user_id="-1">
  <theme name="night"></theme>
  <resources>
    <sign_language toggle="false"></sign_language>
    <subtitles toggle="false"></subtitles>
    <transcription toggle="false"></transcription>
    <dubbing toggle="false"></dubbing>
  </resources>
  <languages>
    <language lang="spanish" order="1"></language>
  </languages>
</settings>
